name: example_generate_pdf
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # formatação de dinheiro/datas
  intl: ^0.16.1
  # impressão do PDF
  printing: ^3.5.0
  # geração do PDF
  pdf: ^1.9.0
  
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true 
   
  assets:
    - assets/